language: node_js
node_js:
  - 9.8.0
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: u5Xwp5SW9xHCoMi1Z0QV0znDDeJ4y49SjHdDKoqc9O9gwYZ8dmLnYsZz41U2bDpcvPd9XOUy0cZW+jITq7IO1zsD6ZDf5IDsPYUwFf/8tpXOZVBQjJg0CPZozQKrQd+5T9LaXF7s+1ZbK9+1pGs9fBLyHJKfRQlV/T/gMYDKz3CdF+cGTtm49jxl0dCsk3BIgymqvLr7YIj0f+T2AHqveeIJ9W4h4rCCgKhNbh0MBjhcpNzBp0R4Mwij2azgxM7eb0KaNzSBX/mtZCJ5xHbaJOPLtFbXG1roRmju5V2lCdD3Jj1Y1xk4UOc5JkbZG8l0FHPQOA70oJDGviWL9KL1KwKjR+lAl5eoBHBvGil+2tKNjzxRrReTiRkUDHgUNLU09BFV1hihhQf/dXDurrCduzC3IpJIIUlAsJ6r5uf+KKhlZnqHfBT2me/v5AoaqTGoH0rqpDt8nGi3xpga4hLtsYzwtOU6RdKIU3yO3P5zISM4v77VVlhEIYL3YCP1eQOwmDeLdKy+hlcGACeyAbGU6fbatXm9QkYSgFjbSnie9cOFv7K/ViEW9OjZK5NLncP32t6w9Qnr4q10z8TOP3UdnR8hCjV71YUmsi7/tZCBHGyWT5/AUz/rN/UsoonoaDAgDJOOxBGgkHDosUHZMkJqHUkZ4EFLcYuALNxwS2aW7KM=
  app: ideashub-client
  on: master
  run:
    - npm start
